version: "3.8"

services:
  # client:
  #   build:
  #     context: .
  #     target: dev
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 3003:3003

  next-prisma:
    build: ./
    container_name: next-prisma-c
    ports:
      - 3003:3003
    volumes:
      - ./next-prisma:/app
    stdin_open: true
    tty: true
