import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { poppins } from "./fonts";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children} <Toaster position="top-center" />
      </body>
    </html>
  );
}
